decanter-agent:
    build: decanter-agent/.
    ports:
    - 4560:4560
    links:
    - kafka
decanter-server:
    build: decanter-server/.
    ports:
    - 8181:8181
    links:
    - kafka
kafka:
    image: spotify/kafka
    ports:
    - 9092:9092
